
"""
Mostly copy-paste from DINO/timm library.
https://github.com/facebookresearch/dino/blob/main/vision_transformer.py
https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py
"""
import math
from functools import partial

import torch
import torch.nn as nn

import einops

import pdb

from mmcr.cifar_stl.data import calc_whiten_mx


def embed_dist_logging(x, name, prefix=""):    
    # with torch.no_grad():
    #     # check how similar image patch centroids are. gives a rough sense of the distribution of embeddings
    #     x_norm = torch.nn.functional.normalize(x, dim=-1)
    #     x_norm_mean = torch.nn.functional.normalize(x_norm.mean(dim=1), dim=-1)
        
    #     # relation of patches to their centroids
    #     x_sims = (x_norm @ x_norm_mean.T).permute((0, 2, 1))
    #     x_sims = torch.diagonal(x_sims, dim1=0, dim2=1)

    #     print(f"{prefix}HERE ({name}): \t{(x_norm_mean @ x_norm_mean.T).abs().min()} ({x_sims.min()} {x_sims.abs().min()} {x_sims.max()}, {x_sims.mean()})")
    return


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # https://github.com/facebookresearch/dino/blob/main/utils.py
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def drop_path(x, drop_prob: float = 0., training: bool = False):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

        # m = 0
        # s = 0.5
        # torch.nn.init.normal_(self.fc1.weight, mean=m, std=s)
        # torch.nn.init.normal_(self.fc2.weight, mean=m, std=s)
        # if self.fc1.bias is not None:
        #     torch.nn.init.zeros_(self.fc1.bias)
        # if self.fc2.bias is not None:
        #     torch.nn.init.zeros_(self.fc2.bias)

        # torch.nn.init.orthogonal_(self.fc1.weight)
        # torch.nn.init.orthogonal_(self.fc2.weight)


    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        m = 0
        s = 1
        torch.nn.init.normal_(self.qkv.weight, mean=m, std=s)
        torch.nn.init.normal_(self.proj.weight, mean=m, std=s)
        if self.qkv.bias is not None:
            torch.nn.init.zeros_(self.qkv.bias)
        if self.proj.bias is not None:
            torch.nn.init.zeros_(self.proj.bias)


    def forward(self, x):

        embed_dist_logging(x, "pre-SDPA", "\t\t")


        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        # attn = (q @ k.transpose(-2, -1)) * self.scale
        # attn = attn.softmax(dim=-1)
        # attn = self.attn_drop(attn)
        # x = attn @ v
        
        x = torch.nn.functional.scaled_dot_product_attention(q, k, v, dropout_p=self.attn_drop.p if self.training else 0., scale=self.scale)

        x = x.transpose(1, 2).reshape(B, N, C)
        

        embed_dist_logging(x, "post-SDPA", "\t\t")
        
        
        x = self.proj(x)

        embed_dist_logging(x, "post-proj", "\t\t")
        # pdb.set_trace()



        x = self.proj_drop(x)
        return x


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x):
        y = self.attn(self.norm1(x))

        embed_dist_logging(y, "post-attn", "\t")

        x = x + self.drop_path(y)

        embed_dist_logging(x, f"post-res (1)", "\t")
        
        foo = self.norm2(x)
        embed_dist_logging(foo, f"post-norm", "\t")
        foo = self.mlp(foo)
        embed_dist_logging(foo, "post-mlp", "\t")


        x = x + self.drop_path(foo)
        embed_dist_logging(x, "post-res (2)", "\t")

        return x


class PatchEmbed(nn.Module):
    """ Image to Patch Embedding
    """
    def __init__(self, img_size=224, patch_size=16, patch_stride=16, in_chans=3, embed_dim=768):
        super().__init__()
        self.img_size = img_size
        self.patch_size = patch_size
        self.patch_stride = patch_stride
        self.in_chans = in_chans

        # TODO: use unfold for this instead
        # num_patches = (img_size // patch_size) * (img_size // patch_size)
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_stride)
        with torch.no_grad():
            tmp = torch.zeros((in_chans, img_size, img_size))
            shp = self.proj(tmp).shape
            self.num_patches = shp[1] * shp[2]
        
        self.proj = nn.Linear(in_chans * patch_size * patch_size, embed_dim)
        if self.proj.bias is not None:
            torch.nn.init.zeros_(self.proj.bias)

        # TODO: probably just save this to disk? annoying to have to recompute each time
        self.whiten_mx, self.mean = calc_whiten_mx(patch_size, patch_stride)
        self.whiten_mx = self.whiten_mx.to("cuda")
        self.mean = self.mean.to("cuda")


    def forward(self, x):
        # generate patches, center + whiten, L2 normalize, then apply a linear layer
        patches = torch.nn.functional.unfold(x, self.patch_size, stride=self.patch_stride)
        patches = einops.rearrange(patches, "A (B C) D -> A B C D", B=self.in_chans)
        patches = patches - self.mean.unsqueeze(0).unsqueeze(-1)
        
        
        patches = einops.rearrange(patches, "A B C D -> A D (B C)")
        patches = patches @ self.whiten_mx

        patches = torch.nn.functional.normalize(patches, dim=-1)
        
        embed_dist_logging(patches, "pre-proj")

        patches = self.proj(patches)


        # NOTE: by comparing p_sims[0, :, ...] and proj_sims[0, :, ...] we see that before the Linear layer here 
        # all patches for an image are somewhat similar to their centroid (0 < cosine sim < 0.3) and nearly orthogonal to the centroids of the patches of all other images
        # after the linear layer, nearly all centroids and embeddings are squashed down into the same space:
        # (proj_mean @ proj_mean.T).abs().min() --> 0.916
        # (p_mean @ p_mean.T).abs().min() --> 1.7794e-05

        # pdb.set_trace()


        return patches


class VisionTransformer(nn.Module):
    """ Vision Transformer """
    def __init__(self, img_size=32, patch_size=16, patch_stride=0, in_chans=3, embed_dim=768, depth=12,
                 num_heads=12, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop_rate=0., attn_drop_rate=0.,
                 drop_path_rate=0., norm_layer=nn.LayerNorm, enable_cls=False, **kwargs):
        super().__init__()
        self.num_features = self.embed_dim = embed_dim

        if patch_stride <= 0:
            patch_stride = patch_size
        self.patch_stride = patch_stride

        self.patch_embed = PatchEmbed(img_size=img_size, patch_size=patch_size, patch_stride=self.patch_stride, in_chans=in_chans, embed_dim=embed_dim)
        num_patches = self.patch_embed.num_patches

        self.enable_cls = enable_cls
        if enable_cls:
            self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
            # trunc_normal_(self.cls_token, std=.02)
            self.pos_embed = nn.Parameter(torch.zeros(1, num_patches + 1, embed_dim))
        else:
            self.pos_embed = nn.Parameter(torch.zeros(1, num_patches, embed_dim))
        self.pos_drop = nn.Dropout(p=drop_rate)

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])
        self.norm = norm_layer(embed_dim)

    #     trunc_normal_(self.pos_embed, std=.02)
    #     self.apply(self._init_weights)

    # def _init_weights(self, m):
    #     if isinstance(m, nn.Linear):
    #         trunc_normal_(m.weight, std=.02)
    #         if isinstance(m, nn.Linear) and m.bias is not None:
    #             nn.init.constant_(m.bias, 0)
    #     elif isinstance(m, nn.LayerNorm):
    #         nn.init.constant_(m.bias, 0)
    #         nn.init.constant_(m.weight, 1.0)

    def interpolate_pos_encoding(self, x, w, h):
        if self.enable_cls:
            npatch = x.shape[1] - 1
            N = self.pos_embed.shape[1] - 1
        else:
            npatch = x.shape[1]
            N = self.pos_embed.shape[1]
        if npatch == N and w == h:
            return self.pos_embed
        
        if self.enable_cls:
            class_pos_embed = self.pos_embed[:, 0]
            patch_pos_embed = self.pos_embed[:, 1:]
        else:
            patch_pos_embed = self.pos_embed
        dim = x.shape[-1]
        w0 = w // self.patch_embed.patch_size
        h0 = h // self.patch_embed.patch_size
        # we add a small number to avoid floating point error in the interpolation
        # see discussion at https://github.com/facebookresearch/dino/issues/8
        w0, h0 = w0 + 0.1, h0 + 0.1
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(0, 3, 1, 2),
            scale_factor=(w0 / math.sqrt(N), h0 / math.sqrt(N)),
            mode='bicubic',
        )
        assert int(w0) == patch_pos_embed.shape[-2] and int(h0) == patch_pos_embed.shape[-1]
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        if self.enable_cls:
            return torch.cat((class_pos_embed.unsqueeze(0), patch_pos_embed), dim=1)
        else:
            return patch_pos_embed

    def prepare_tokens(self, x):
        B, nc, w, h = x.shape
        x = self.patch_embed(x)  # patch linear embedding

        # add the [CLS] token to the embed patch tokens
        if self.enable_cls:
            cls_tokens = self.cls_token.expand(B, -1, -1)
            x = torch.cat((cls_tokens, x), dim=1)

        # add positional encoding to each token    
        x = x + self.interpolate_pos_encoding(x, w, h)

        return self.pos_drop(x)
        
    def forward(self, x):
        x = self.prepare_tokens(x)
        
        embed_dist_logging(x, "post-patch embed")
        
        for idx, blk in enumerate(self.blocks):
            x = blk(x)
            embed_dist_logging(x, f"post block {idx}")
        # pdb.set_trace() 


        x = self.norm(x)
        
        embed_dist_logging(x, "post norm")
        # pdb.set_trace() 


        if self.enable_cls:
            return x[:, 0]
        else:
            return x

    # def get_last_selfattention(self, x):
    #     x = self.prepare_tokens(x)
    #     for i, blk in enumerate(self.blocks):
    #         if i < len(self.blocks) - 1:
    #             x = blk(x)
    #         else:
    #             # return attention of the last block
    #             return blk(x, return_attention=True)

    def get_intermediate_layers(self, x, n=1):
        x = self.prepare_tokens(x)
        # we return the output tokens from the `n` last blocks
        output = []
        for i, blk in enumerate(self.blocks):
            x = blk(x)
            if len(self.blocks) - i <= n:
                output.append(self.norm(x))
        return output


def vit_tiny(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


def vit_small(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=384, depth=12, num_heads=6, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


def vit_base(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=768, depth=12, num_heads=12, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


class DINOHead(nn.Module):
    def __init__(self, in_dim, out_dim, use_bn=False, norm_last_layer=True, nlayers=3, hidden_dim=2048, bottleneck_dim=256):
        super().__init__()
        nlayers = max(nlayers, 1)
        if nlayers == 1:
            self.mlp = nn.Linear(in_dim, bottleneck_dim)
        else:
            layers = [nn.Linear(in_dim, hidden_dim)]
            if use_bn:
                layers.append(nn.BatchNorm1d(hidden_dim))
            layers.append(nn.GELU())
            for _ in range(nlayers - 2):
                layers.append(nn.Linear(hidden_dim, hidden_dim))
                if use_bn:
                    layers.append(nn.BatchNorm1d(hidden_dim))
                layers.append(nn.GELU())
            layers.append(nn.Linear(hidden_dim, bottleneck_dim))
            self.mlp = nn.Sequential(*layers)
        self.apply(self._init_weights)
        self.last_layer = nn.utils.weight_norm(nn.Linear(bottleneck_dim, out_dim, bias=False))
        self.last_layer.weight_g.data.fill_(1)
        if norm_last_layer:
            self.last_layer.weight_g.requires_grad = False

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = self.mlp(x)
        x = nn.functional.normalize(x, dim=-1, p=2)
        x = self.last_layer(x)
        return x